version: '3'

services:
  db:
    build: ./db
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: ./app
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ../gopkg:/bin/gopkg
      - ./app/run_app.sh:/bin/run_app.sh


volumes:
  postgres-data:

networks:
  app-network: